"""new fields in user model

Revision ID: 729f8cb0989b
Revises: 051cf6595917
Create Date: 2018-09-01 11:35:54.441359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729f8cb0989b'
down_revision = '051cf6595917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
